# Generated by Django 5.0.7 on 2024-07-29 21:12

import core.core_attrs
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElixirOfLinks',
            fields=[
                ('timestamp', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.core_attrs.CoreAttrs),
        ),
    ]
